/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef FLURRY_AUTODEFS_H
#define FLURRY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FLURRY_NAME "Flurry"
#define S3E_EXT_FLURRY_HASH 0xfdb1a7c9

#endif /* !FLURRY_AUTODEFS_H */
